---
settings:
  parallel: true

driver:
  name: vagrant
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  nodes_path: 'test/integration/nodes'
  data_bags_path: 'test/integration/data_bags'
  environments_path: 'test/integration/environments'
  roles_path: 'test/integration/roles'

verifier:
  name: inspec

platforms:
  # - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[test-proxysql::default]
      - role[admin_variables]
      - role[mysql_variables]
      - role[mysql_servers]
      - role[mysql_users]
      - role[mysql_query_rules]
      - role[mysql_replication_hostgroups]

  - name: 2mysql
    run_list:
      - recipe[test-proxysql::2mysql]
