---
settings:
  parallel: true

driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  nodes_path: 'test/integration/nodes'
  data_bags_path: 'test/integration/data_bags'
  environments_path: 'test/integration/environments'
  roles_path: 'test/integration/roles'

verifier:
  name: inspec

platforms:
  - name: centos
    driver_plugin: docker
    driver:
      image: ernestasposkus/centos7
      run_command: /usr/lib/systemd/systemd
      run_options: '--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'
  # - name: ubuntu
  #   driver_plugin: docker
  #   driver:
  #     image: ernestasposkus/ubuntu1604
  #     run_command: '/lib/systemd/systemd'
  #     run_options: '--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'

suites:
  - name: default
    run_list:
      - recipe[test-proxysql::default]
      - role[admin_variables]
      - role[mysql_variables]
      - role[mysql_servers]
      - role[mysql_users]
      - role[mysql_query_rules]
      - role[mysql_replication_hostgroups]

  - name: 2mysql
    run_list:
      - recipe[test-proxysql::2mysql]
